"""auto update

Revision ID: 7ac9b11b3a25
Revises: 7afcf81cfc16
Create Date: 2026-03-06 11:09:37.661002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ac9b11b3a25'
down_revision: Union[str, Sequence[str], None] = '7afcf81cfc16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorized_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id_tg', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('added_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorized_roles_id'), 'authorized_roles', ['id'], unique=False)
    op.create_table('bot_filters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filter_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('buttons_json', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('assigned_chat_ids', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_filters_id'), 'bot_filters', ['id'], unique=False)
    op.create_table('chat_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('chat_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('added_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_groups_id'), 'chat_groups', ['id'], unique=False)
    op.create_table('protection_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('setting_key', sa.String(), nullable=False),
    sa.Column('setting_value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protection_settings_id'), 'protection_settings', ['id'], unique=False)
    op.create_table('site_commands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('command_name', sa.String(), nullable=False),
    sa.Column('site_name', sa.String(), nullable=False),
    sa.Column('site_url', sa.String(), nullable=False),
    sa.Column('message_text', sa.String(), nullable=True),
    sa.Column('button_text', sa.String(), nullable=True),
    sa.Column('button_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_commands_id'), 'site_commands', ['id'], unique=False)
    op.create_table('warnings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id_tg', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('last_warning_date', sa.String(), nullable=True),
    sa.Column('mute_end', sa.String(), nullable=True),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warnings_id'), 'warnings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warnings_id'), table_name='warnings')
    op.drop_table('warnings')
    op.drop_index(op.f('ix_site_commands_id'), table_name='site_commands')
    op.drop_table('site_commands')
    op.drop_index(op.f('ix_protection_settings_id'), table_name='protection_settings')
    op.drop_table('protection_settings')
    op.drop_index(op.f('ix_chat_groups_id'), table_name='chat_groups')
    op.drop_table('chat_groups')
    op.drop_index(op.f('ix_bot_filters_id'), table_name='bot_filters')
    op.drop_table('bot_filters')
    op.drop_index(op.f('ix_authorized_roles_id'), table_name='authorized_roles')
    op.drop_table('authorized_roles')
    # ### end Alembic commands ###